import { Store, Product } from './types';
import { JAMSHEDPUR_ZONES } from './geo';

export const SEED_STORES: Store[] = [
  // --- 1. P&M HI-TECH CITY CENTRE MALL, BISTUPUR (TIER 1 CRITICAL) ---
  {
    id: 'store_pnm_westside',
    merchantId: 'm_pnm_01',
    name: 'Westside - P&M Hi-Tech Mall',
    brand: 'Westside / Tata Trent',
    address: 'Ground & 1st Floor, P&M Hi-Tech Mall, Outer Circle Rd, Bistupur',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'P&M Hi-Tech City Centre Mall',
    coordinates: JAMSHEDPUR_ZONES.PNM_MALL_BISTUPUR,
    rating: 4.8,
    totalRatings: 1420,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 6628100',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Fast-Dispatch', 'Mall-Exclusive', 'All-Segments'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS', 'FOOTWEAR'],
    googleRating: 4.8,
    googleReviewCount: 1420,
    approxStoreSqFt: 18000
  },
  {
    id: 'store_pnm_pantaloons',
    merchantId: 'm_pnm_02',
    name: 'Pantaloons - P&M Mall',
    brand: 'Pantaloons / Aditya Birla',
    address: '1st Floor, P&M Hi-Tech Mall, Bistupur',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'P&M Hi-Tech City Centre Mall',
    coordinates: JAMSHEDPUR_ZONES.PNM_MALL_BISTUPUR,
    rating: 4.7,
    totalRatings: 1890,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2420911',
    imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=800&q=80',
    tags: ['Showroom-Verified', 'Multi-Brand'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS', 'ETHNIC'],
    googleRating: 4.7,
    googleReviewCount: 1890,
    approxStoreSqFt: 15000
  },
  {
    id: 'store_pnm_soch',
    merchantId: 'm_pnm_03',
    name: 'Soch Ethnic Studio - P&M Mall',
    brand: 'Soch',
    address: 'G21 & G22, Ground Floor, P&M Hi-Tech Mall, Bistupur',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'P&M Hi-Tech City Centre Mall',
    coordinates: JAMSHEDPUR_ZONES.PNM_MALL_BISTUPUR,
    rating: 4.9,
    totalRatings: 340,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 2439811',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    tags: ['Ethnic-Exclusive', 'Premium-Silk'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['WOMEN', 'ETHNIC'],
    googleRating: 4.9,
    googleReviewCount: 340,
    approxStoreSqFt: 3200
  },
  {
    id: 'store_pnm_blackberrys',
    merchantId: 'm_pnm_04',
    name: 'Blackberrys Menswear - P&M Mall',
    brand: 'Blackberrys',
    address: 'Shop 108, 1st Floor, P&M Hi-Tech Mall, Bistupur',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'P&M Hi-Tech City Centre Mall',
    coordinates: JAMSHEDPUR_ZONES.PNM_MALL_BISTUPUR,
    rating: 4.6,
    totalRatings: 280,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 2427700',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    tags: ['Suits', 'Formalwear', 'Express-Pick'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'FORMAL'],
    googleRating: 4.6,
    googleReviewCount: 280,
    approxStoreSqFt: 2500
  },

  // --- 2. BISTUPUR MAIN ROAD & MARKET (TIER 1 CRITICAL) ---
  {
    id: 'store_bistupur_manyavar_flagship',
    merchantId: 'm_bis_01',
    name: 'Manyavar & Mohey Flagship Bistupur',
    brand: 'Manyavar',
    address: 'Heritage Plaza, Bistupur Boulevard Main Road',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'Bistupur Main Road',
    coordinates: JAMSHEDPUR_ZONES.BISTUPUR_MAIN,
    rating: 4.9,
    totalRatings: 610,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 2439900',
    imageUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
    tags: ['Wedding', 'Festive-Sherwani', 'Fast-Dispatch'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'ETHNIC'],
    googleRating: 4.9,
    googleReviewCount: 610,
    approxStoreSqFt: 5500
  },
  {
    id: 'store_bistupur_fabindia',
    merchantId: 'm_bis_02',
    name: 'Fabindia - Bistupur Exclusive',
    brand: 'Fabindia',
    address: 'Holding No 14, Main Road Bistupur, Opp. Regal Cinema',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'Bistupur Main Road',
    coordinates: JAMSHEDPUR_ZONES.BISTUPUR_MAIN,
    rating: 4.7,
    totalRatings: 490,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2423311',
    imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80',
    tags: ['Organic-Cotton', 'Handloom', 'Fast-30-Min'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'ETHNIC'],
    googleRating: 4.7,
    googleReviewCount: 490,
    approxStoreSqFt: 4000
  },
  {
    id: 'store_bistupur_helios_watches',
    merchantId: 'm_bis_04',
    name: 'Helios – The Luxury Watch Store Bistupur',
    brand: 'Titan / Helios / Fossil',
    address: 'Shop 8, Bistupur Market Square',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    mallOrMarket: 'Bistupur Main Road',
    coordinates: JAMSHEDPUR_ZONES.BISTUPUR_MAIN,
    rating: 4.8,
    totalRatings: 310,
    isOpen: true,
    averagePrepTimeMinutes: 4,
    contactNumber: '+91 657 2421900',
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    tags: ['Watches', 'Fast-Dispatch', 'Accessories'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ACCESSORY_SPECIALIST',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['ACCESSORIES', 'WATCHES'],
    googleRating: 4.8,
    googleReviewCount: 310,
    approxStoreSqFt: 1800
  },

  // --- 3. SAKCHI COMMERCIAL CLUSTER & HIGH STREET (TIER 1 CRITICAL) ---
  {
    id: 'store_sakchi_vmart_ambagan',
    merchantId: 'm_sak_01',
    name: 'V-Mart Mega Fashion - Sakchi Ambagan',
    brand: 'V-Mart',
    address: 'Ambagan Grounds, Sakchi High Street',
    locality: 'Sakchi',
    city: 'Jamshedpur',
    mallOrMarket: 'Sakchi Ambagan',
    coordinates: JAMSHEDPUR_ZONES.SAKCHI_AMBAGAN,
    rating: 4.5,
    totalRatings: 3450,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2234001',
    imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=800&q=80',
    tags: ['Mass-Value', 'Huge-Stock', 'Family-Store'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MASS_VALUE',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS', 'FOOTWEAR'],
    googleRating: 4.5,
    googleReviewCount: 3450,
    approxStoreSqFt: 22000
  },
  {
    id: 'store_sakchi_trends_basant',
    merchantId: 'm_sak_03',
    name: 'Reliance TRENDS - Basant Talkies Sakchi',
    brand: 'Reliance TRENDS',
    address: 'Near Basant Talkies Complex, Sakchi Market',
    locality: 'Sakchi',
    city: 'Jamshedpur',
    mallOrMarket: 'Sakchi Market',
    coordinates: JAMSHEDPUR_ZONES.SAKCHI_MARKET,
    rating: 4.6,
    totalRatings: 1120,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2238810',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    tags: ['Fast-30-Min', 'Daily-Hero', 'Trending'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS'],
    googleRating: 4.6,
    googleReviewCount: 1120,
    approxStoreSqFt: 12000
  },

  // --- 4. GAMHARIA MASTER FASHION CENSUS (EXPANDED INDUSTRIAL CORRIDOR) ---
  {
    id: 'store_gamharia_citi_style',
    merchantId: 'm_gam_01',
    name: 'CITI STYLE - GAMHARIA Mega Fashion',
    brand: 'Citi Style',
    address: 'Tata-Kandra Main Road, Near Lal Building, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Gamharia Main Corridor',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.6,
    totalRatings: 7180, // Over 7,000 verified Google reviews
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 2389100',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Mega-Anchor', '7k-Reviews', 'Family-Store', 'Fast-30-Min'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MASS_VALUE',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS', 'FOOTWEAR'],
    googleRating: 4.6,
    googleReviewCount: 7180,
    approxStoreSqFt: 16000
  },
  {
    id: 'store_gamharia_zudio',
    merchantId: 'm_gam_02',
    name: 'Zudio - Gamharia Tata Trent',
    brand: 'Zudio / Tata',
    address: 'Identity Complex, Tata-Kandra Road, Near Auto Cluster Phase VII, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Auto Cluster Corridor',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.7,
    totalRatings: 2450,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 657 2382190',
    imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=800&q=80',
    tags: ['Tata-Zudio', 'Trending-GenZ', 'Fast-30-Min'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'BUDGET_FRIENDLY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS', 'FOOTWEAR'],
    googleRating: 4.7,
    googleReviewCount: 2450,
    approxStoreSqFt: 10000
  },
  {
    id: 'store_gamharia_iconic_mens_wear',
    merchantId: 'm_gam_03',
    name: "ICONIC MEN'S WEAR - Gamharia",
    brand: 'Iconic Menswear',
    address: 'Mahabir Trade Center, Near Teachers Training School, Tata-Kandra Main Rd, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Mahabir Trade Center',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 5.0, // 5.0 rating in verified business listing
    totalRatings: 57,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 98351 90812',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    tags: ['Top-Rated-5.0', 'Mens-Fashion', 'Fast-Dispatch'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'INDEPENDENT_BOUTIQUE',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'MANUAL_APP_POS',
    fashionSegments: ['MEN', 'SHIRTS', 'JEANS'],
    googleRating: 5.0,
    googleReviewCount: 57,
    approxStoreSqFt: 2200
  },
  {
    id: 'store_gamharia_brands_heaven',
    merchantId: 'm_gam_04',
    name: 'Brands Heaven — Your Fashion Destination',
    brand: 'Brands Heaven',
    address: 'Lal Building Chowk, Main Road, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Lal Building Area',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.8,
    totalRatings: 190,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 98357 22001',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
    tags: ['Multi-Brand', 'Youth-Denim'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'INDEPENDENT_BOUTIQUE',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'EXCEL_BARCODE_SYNC',
    fashionSegments: ['MEN', 'WOMEN'],
    googleRating: 4.8,
    googleReviewCount: 190,
    approxStoreSqFt: 2800
  },
  {
    id: 'store_gamharia_sen_shoes',
    merchantId: 'm_gam_05',
    name: 'Sen Shoes & Footwear Gamharia',
    brand: 'Sen Shoes / Campus / Sparx',
    address: 'Manglam Tower, Tata-Kandra Main Road, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Manglam Tower',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.7,
    totalRatings: 310,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 94311 00291',
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    tags: ['Footwear-Anchor', 'Sneakers-Sandals'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'ACCESSORY_SPECIALIST',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'EXCEL_BARCODE_SYNC',
    fashionSegments: ['FOOTWEAR'],
    googleRating: 4.7,
    googleReviewCount: 310,
    approxStoreSqFt: 2500
  },
  {
    id: 'store_gamharia_dhane_footwear_bags',
    merchantId: 'm_gam_06',
    name: 'Dhane Footwear & Bags',
    brand: 'Dhane / Skybags / Wildcraft',
    address: 'Shop No. 36, Gamharia Main Market',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Gamharia Market',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.6,
    totalRatings: 145,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 98353 11899',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    tags: ['Bags-Luggage', 'Shoes-Combo'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'ACCESSORY_SPECIALIST',
    priceBand: 'MASS_VALUE',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'MANUAL_APP_POS',
    fashionSegments: ['FOOTWEAR', 'BAGS_LUGGAGE'],
    googleRating: 4.6,
    googleReviewCount: 145,
    approxStoreSqFt: 1800
  },
  {
    id: 'store_gamharia_shree_mahabir_jewellers',
    merchantId: 'm_gam_07',
    name: 'Shree Mahabir Jewellers Gamharia',
    brand: 'Shree Mahabir',
    address: 'Behind Gamharia Lal Building, Tata-Kandra Road',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Lal Building Area',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.8,
    totalRatings: 210,
    isOpen: true,
    averagePrepTimeMinutes: 4,
    contactNumber: '+91 657 2387711',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    tags: ['Fashion-Jewellery', 'Gold-Silver-Accessories'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'ACCESSORY_SPECIALIST',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['JEWELLERY', 'ACCESSORIES'],
    googleRating: 4.8,
    googleReviewCount: 210,
    approxStoreSqFt: 1600
  },
  {
    id: 'store_gamharia_agarwal_uniforms',
    merchantId: 'm_gam_08',
    name: 'Agarwal Uniforms & School Institutional Apparel',
    brand: 'Agarwal Uniforms',
    address: 'Sabji Market Road, Dhirajganj, Gamharia',
    locality: 'Gamharia',
    city: 'Jamshedpur',
    mallOrMarket: 'Dhirajganj Sabji Market',
    coordinates: JAMSHEDPUR_ZONES.GAMHARIA_TATA_KANDRA,
    rating: 4.7,
    totalRatings: 380,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 94313 77012',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    tags: ['Institutional', 'School-Bags-Uniforms'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'WHOLESALE_VALUE',
    priceBand: 'MASS_VALUE',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'MANUAL_APP_POS',
    fashionSegments: ['UNIFORMS', 'KIDS', 'BAGS_LUGGAGE'],
    googleRating: 4.7,
    googleReviewCount: 380,
    approxStoreSqFt: 3000
  },

  // --- 5. JUGSALAI READMYMADE & WHOLESALE (TIER 1 CRITICAL) ---
  {
    id: 'store_jugsalai_trends',
    merchantId: 'm_jug_01',
    name: 'Reliance TRENDS - Jugsalai Station Road',
    brand: 'Reliance TRENDS',
    address: 'Station Road, Near Jugsalai Overbridge',
    locality: 'Jugsalai',
    city: 'Jamshedpur',
    mallOrMarket: 'Jugsalai Station Road',
    coordinates: JAMSHEDPUR_ZONES.JUGSALAI_STATION_RD,
    rating: 4.6,
    totalRatings: 840,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2291002',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Fast-Dispatch', 'Value-Apparel'],
    acquisitionTier: 'TIER_1_CRITICAL',
    businessType: 'ORGANIZED_CHAIN',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'API_CONNECTED',
    fashionSegments: ['MEN', 'WOMEN', 'KIDS'],
    googleRating: 4.6,
    googleReviewCount: 840,
    approxStoreSqFt: 9000
  },

  // --- 6. SONARI BOUTIQUE DISTRICT (TIER 2 HIGH) ---
  {
    id: 'store_sonari_needlehat',
    merchantId: 'm_son_01',
    name: 'needleHat Fashion Boutique & Studio',
    brand: 'needleHat Couture',
    address: 'Plot 18, Near Sonari Community Centre, Aerodrome Road',
    locality: 'Sonari',
    city: 'Jamshedpur',
    mallOrMarket: 'Sonari West District',
    coordinates: JAMSHEDPUR_ZONES.SONARI_AIRPORT,
    rating: 4.9,
    totalRatings: 180,
    isOpen: true,
    averagePrepTimeMinutes: 5,
    contactNumber: '+91 98353 44101',
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
    tags: ['Designer-Boutique', 'Custom-Fits', 'Fast-30-Min'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'INDEPENDENT_BOUTIQUE',
    priceBand: 'PREMIUM_LUXURY',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'MANUAL_APP_POS',
    fashionSegments: ['WOMEN', 'DRESSES', 'COUTURE'],
    googleRating: 4.9,
    googleReviewCount: 180,
    approxStoreSqFt: 1600
  },

  // --- 7. MANGO / ZAKIR NAGAR (TIER 2 HIGH) ---
  {
    id: 'store_mango_vastrea',
    merchantId: 'm_mng_01',
    name: 'Vastrea Premium Clothing Brand & Boutique',
    brand: 'Vastrea',
    address: 'Dimna Road, Near Chepa Pul, Mango',
    locality: 'Mango',
    city: 'Jamshedpur',
    mallOrMarket: 'Mango Dimna Road',
    coordinates: JAMSHEDPUR_ZONES.MANGO_DIMNA_RD,
    rating: 4.9,
    totalRatings: 260,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 94311 88400',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    tags: ['Premium-Brand', 'Ethnic-Modern'],
    acquisitionTier: 'TIER_2_HIGH',
    businessType: 'INDEPENDENT_BOUTIQUE',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'EXCEL_BARCODE_SYNC',
    fashionSegments: ['WOMEN', 'MEN', 'ETHNIC'],
    googleRating: 4.9,
    googleReviewCount: 260,
    approxStoreSqFt: 2200
  },

  // --- 8. GOLMURI (TIER 3 MEDIUM) ---
  {
    id: 'store_golmuri_qila_heritage',
    merchantId: 'm_gol_01',
    name: 'QILA HERITAGE Fashion House',
    brand: 'Qila Heritage',
    address: 'Clock Tower Square, Golmuri Main Road',
    locality: 'Golmuri',
    city: 'Jamshedpur',
    mallOrMarket: 'Golmuri Market',
    coordinates: JAMSHEDPUR_ZONES.GOLMURI_CHOWK,
    rating: 4.7,
    totalRatings: 195,
    isOpen: true,
    averagePrepTimeMinutes: 6,
    contactNumber: '+91 657 2341901',
    imageUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
    tags: ['Heritage-Apparel', 'Festive'],
    acquisitionTier: 'TIER_3_MEDIUM',
    businessType: 'INDEPENDENT_BOUTIQUE',
    priceBand: 'MID_PREMIUM',
    onboardingStatus: 'LIVE_30M_ACTIVE',
    posCapability: 'MANUAL_APP_POS',
    fashionSegments: ['MEN', 'WOMEN', 'ETHNIC'],
    googleRating: 4.7,
    googleReviewCount: 195,
    approxStoreSqFt: 1800
  }
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_zudio_relaxed_tee',
    brand: 'ZUDIO',
    title: 'Men Sage Green Textured Relaxed Fit Drop-Shoulder T-shirt',
    description: 'Textured knit pure cotton relaxed t-shirt with ribbed crew neck. Super fast 30-min delivery from Zudio Gamharia Auto Cluster.',
    category: 't-shirts',
    gender: 'men',
    mrp: 999,
    basePrice: 499,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: '100% Cotton Waffle Knit',
    pattern: 'Textured Solid',
    occasion: 'casual',
    rating: 4.6,
    reviewCount: 3200,
    tags: ['Zudio Gamharia', 'GenZ Value', 'Fast-30-Min'],
    variants: [
      { id: 'var_zud_s_grn', productId: 'prod_zudio_relaxed_tee', sku: 'ZUD-WAFF-S', size: 'S', color: 'Sage Green', colorHex: '#8FBC8F', mrp: 999, price: 499 },
      { id: 'var_zud_m_grn', productId: 'prod_zudio_relaxed_tee', sku: 'ZUD-WAFF-M', size: 'M', color: 'Sage Green', colorHex: '#8FBC8F', mrp: 999, price: 499 },
      { id: 'var_zud_l_grn', productId: 'prod_zudio_relaxed_tee', sku: 'ZUD-WAFF-L', size: 'L', color: 'Sage Green', colorHex: '#8FBC8F', mrp: 999, price: 499 },
      { id: 'var_zud_xl_grn', productId: 'prod_zudio_relaxed_tee', sku: 'ZUD-WAFF-XL', size: 'XL', color: 'Sage Green', colorHex: '#8FBC8F', mrp: 999, price: 499 }
    ]
  },
  {
    id: 'prod_citi_style_smart_denim',
    brand: 'CITI STYLE',
    title: 'Men Mid-Rise Comfort Stretch Clean Dark Indigo Jeans',
    description: 'Heavyweight cotton stretch denim with reinforced pocket rivets, available directly from Citi Style Gamharia Mega Store.',
    category: 'jeans',
    gender: 'men',
    mrp: 1999,
    basePrice: 999,
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: 'Cotton Poly Elastane',
    pattern: 'Clean Dark Wash',
    occasion: 'casual',
    rating: 4.5,
    reviewCount: 5120,
    tags: ['Citi Style Gamharia', 'Best Value', 'Fast-30-Min'],
    variants: [
      { id: 'var_cs_30_ind', productId: 'prod_citi_style_smart_denim', sku: 'CS-DNM-30', size: '30', color: 'Dark Indigo', colorHex: '#1C2833', mrp: 1999, price: 999 },
      { id: 'var_cs_32_ind', productId: 'prod_citi_style_smart_denim', sku: 'CS-DNM-32', size: '32', color: 'Dark Indigo', colorHex: '#1C2833', mrp: 1999, price: 999 },
      { id: 'var_cs_34_ind', productId: 'prod_citi_style_smart_denim', sku: 'CS-DNM-34', size: '34', color: 'Dark Indigo', colorHex: '#1C2833', mrp: 1999, price: 999 }
    ]
  },
  {
    id: 'prod_black_oxford_shirt',
    brand: 'ICONIC MENS WEAR',
    title: 'Men Slim Fit Solid Pure Cotton Oxford Casual Shirt',
    description: 'Black solid casual shirt, has a spread collar, button placket, 1 curved patch pocket, long regular sleeves, and a curved hem.',
    category: 'shirts',
    gender: 'men',
    mrp: 2999,
    basePrice: 1599,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: '100% Cotton',
    pattern: 'Solid Oxford',
    occasion: 'party',
    rating: 5.0,
    reviewCount: 57,
    tags: ['Iconic Gamharia', '5.0 Star Showroom', 'Fast-30-Min'],
    variants: [
      { id: 'var_boxf_s_blk', productId: 'prod_black_oxford_shirt', sku: 'ICN-OXF-BLK-S', size: 'S', color: 'Black', colorHex: '#111111', mrp: 2999, price: 1599 },
      { id: 'var_boxf_m_blk', productId: 'prod_black_oxford_shirt', sku: 'ICN-OXF-BLK-M', size: 'M', color: 'Black', colorHex: '#111111', mrp: 2999, price: 1599 },
      { id: 'var_boxf_l_blk', productId: 'prod_black_oxford_shirt', sku: 'ICN-OXF-BLK-L', size: 'L', color: 'Black', colorHex: '#111111', mrp: 2999, price: 1599 },
      { id: 'var_boxf_xl_blk', productId: 'prod_black_oxford_shirt', sku: 'ICN-OXF-BLK-XL', size: 'XL', color: 'Black', colorHex: '#111111', mrp: 2999, price: 1599 }
    ]
  },
  {
    id: 'prod_silk_blend_kurta',
    brand: 'MANYAVAR',
    title: 'Men Embroidered Silk Blend Straight Kurta with Churidar',
    description: 'Navy blue straight knee-length kurta, mandarin collar, long sleeves, side slits, accompanied with cream dupion silk churidar.',
    category: 'ethnic',
    gender: 'men',
    mrp: 6999,
    basePrice: 4199,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: 'Silk Blend Jacquard',
    pattern: 'Embroidered',
    occasion: 'festive',
    rating: 4.6,
    reviewCount: 920,
    tags: ['Immediate Festive', 'Bistupur Exclusive'],
    variants: [
      { id: 'var_man_m_nvy', productId: 'prod_silk_blend_kurta', sku: 'MAN-JKT-M', size: 'M', color: 'Navy Blue', colorHex: '#0A192F', mrp: 6999, price: 4199 },
      { id: 'var_man_l_nvy', productId: 'prod_silk_blend_kurta', sku: 'MAN-JKT-L', size: 'L', color: 'Navy Blue', colorHex: '#0A192F', mrp: 6999, price: 4199 },
      { id: 'var_man_xl_nvy', productId: 'prod_silk_blend_kurta', sku: 'MAN-JKT-XL', size: 'XL', color: 'Navy Blue', colorHex: '#0A192F', mrp: 6999, price: 4199 }
    ]
  },
  {
    id: 'prod_soch_chanderi_kurti',
    brand: 'SOCH',
    title: 'Women Maroon & Gold Zari Chanderi Festive Kurti Set',
    description: 'Chanderi silk embroidered straight kurti with palazzo and organza dupatta. Exclusive P&M Mall festive edition.',
    category: 'ethnic',
    gender: 'women',
    mrp: 5999,
    basePrice: 3499,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: 'Chanderi Silk',
    pattern: 'Zari Embroidery',
    occasion: 'festive',
    rating: 4.8,
    reviewCount: 480,
    tags: ['P&M Mall Exclusive', 'Fast-30-Min'],
    variants: [
      { id: 'var_soch_s_mrn', productId: 'prod_soch_chanderi_kurti', sku: 'SOCH-KRT-S', size: 'S', color: 'Maroon', colorHex: '#800000', mrp: 5999, price: 3499 },
      { id: 'var_soch_m_mrn', productId: 'prod_soch_chanderi_kurti', sku: 'SOCH-KRT-M', size: 'M', color: 'Maroon', colorHex: '#800000', mrp: 5999, price: 3499 },
      { id: 'var_soch_l_mrn', productId: 'prod_soch_chanderi_kurti', sku: 'SOCH-KRT-L', size: 'L', color: 'Maroon', colorHex: '#800000', mrp: 5999, price: 3499 }
    ]
  },
  {
    id: 'prod_classic_white_sneakers',
    brand: 'SEN SHOES',
    title: 'Men Perforated White Streetwear Casual Sneakers',
    description: 'Lightweight cushioned low-top sneakers with vulcanized grip sole from Sen Shoes Manglam Tower Gamharia.',
    category: 'footwear',
    gender: 'men',
    mrp: 2499,
    basePrice: 1299,
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80'
    ],
    fabric: 'Synthetic Leather',
    pattern: 'Clean White',
    occasion: 'casual',
    rating: 4.7,
    reviewCount: 310,
    tags: ['Sen Shoes Gamharia', 'Footwear'],
    variants: [
      { id: 'var_snk_8_wht', productId: 'prod_classic_white_sneakers', sku: 'SEN-SNK-8', size: '8', color: 'White', colorHex: '#FFFFFF', mrp: 2499, price: 1299 },
      { id: 'var_snk_9_wht', productId: 'prod_classic_white_sneakers', sku: 'SEN-SNK-9', size: '9', color: 'White', colorHex: '#FFFFFF', mrp: 2499, price: 1299 },
      { id: 'var_snk_10_wht', productId: 'prod_classic_white_sneakers', sku: 'SEN-SNK-10', size: '10', color: 'White', colorHex: '#FFFFFF', mrp: 2499, price: 1299 }
    ]
  }
];
